name: SCA
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]  
 workflow_dispatch:
jobs:
 conviso-sca:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{secrets.CONVISO_API_KEY}}
       FLOW_PROJECT_CODE: ${{secrets.PROJECT_KEY_SCA}}
       FLOW_API_URL: ${{secrets.HOMOLOGA_URL}}
   steps:
   - uses: actions/checkout@v2
   - name: Run SCA
     run: conviso sca run
